name = "testing-sri-sai-speciality-dentalcare"
compatibility_date = "2024-09-23"
main = "index.js"

routes = [
  { pattern = "www.srisaispecialitydentalcare.in", custom_domain = true },
  { pattern = "srisaispecialitydentalcare.in", custom_domain = true }
]

[assets]
directory = "."
binding = "ASSETS"
